### ISSUE TITLE
Hits no longer in Package Management

### ISSUE THREAD

**Issue by hugopeek** [jpdevries/hits#19]
Only HitsPage shows up when searching for Hits.. Will try to install manual to see if the extra still works OK on 2.4.

**Comment by hugopeek** [comment]
Ah, on modx.com I see it's only compatible up to 2.3.x..

**Comment by jpdevries** [comment]
I'll remove the ceiling. It should work on 2.x. 

—

**Comment by jpdevries** [comment]
removed ceiling

**Comment by hugopeek** [comment]
Does it take some time before this is processed in the extra's repository? Right now you still can't find it in the manager and it still says 'up to 2.3.x' on modx.com..

**Comment by jpdevries** [comment]
@hugo well that is odd. the changes don't stick. try again, i updated it to say compatible up to 2.4.

@opengeek not sure where to report package manager bugs doing so here.

### Summary

Quick summary what's this issue about.

### Step to reproduce
- Add a package to MODX package provider and set it to be compatible up to 2.3.
- Update the package and set the compatible up to dropdown back to empty
- click save
- view package
- notice your changes don't stick. package still says compatible up to 2.3.

### Observed behavior

Updates to packages do not stick.

### Expected behavior

Updates to packages should stick.

### Environment

MODX.com

![](http://j4p.us/061U2I26130D/Screen%20Shot%202016-01-25%20at%2010.17.41%20AM.png)

### The problem

![](http://j4p.us/3z110b3g1a3Z/Screen%20Shot%202016-01-25%20at%2010.23.14%20AM.png)

Notice the `<option></option>`. That should be something like `<option value="all"></option>` or `<option value="na">n/a</option>`

**Comment by hugopeek** [comment]
It's showing up now, thanks JP.

**Comment by jpdevries** [comment]
> It's showing up now, thanks JP.

np. I set it to max version 2.4 since I can't remove the max version completely
